### PR TITLE
add a ci badge

### PR DESCRIPTION
**Pull request by gorazdko**

### CODE REVIEW

**Comment by ChristopherA** [comment]
Getting not successful checks.

**Comment by ChristopherA** [comment]
Not all checks are successful.

**Review by ChristopherA — APPROVED** [review]

**Comment by ChristopherA** [comment]
Checks are still failing.

**Comment by gorazdko** [comment]
Yes I'm aware and working on it.

Static analyzers with c/c++ means problems all the time.

**Comment by gorazdko** [comment]
* warning suppressed (alternative: https://sourceforge.net/p/cppcheck/discussion/general/thread/df80458a/)

status: ready

**Comment by ChristopherA** [comment]
Merging, but what happens if you do the forced checks of the alternative? Can you add a backlog issue to check that later?

**Comment by gorazdko** [comment]
> Merging, but what happens if you do the forced checks of the alternative? Can you add a backlog issue to check that later?

CI runs in a virtual environment and unlike on a physical machine it couldn't recognize certain env macros. The second solution points out how to stub macros into the cppcheck command.

> Can you add a backlog issue to check that later?

I can, but I'm not particularly interested in wrestling with a linter in a ci virtual environment as it's hard to debug.

Also note that the linter (using the same version) can give (and does! give) different results even on the same machine. This might have to do with the fact that the linter is grabbed from the apt-get / brew and is a bit older (from 2018, v1.82).

**Pull request merged**
